[versions]
# libraries
junit4 = "4.13.2"
opentest4j = "1.3.0"

junit = "5.6.0"
assertk = "0.23"
commons-text = "1.9"
jackson = "2.11.+"

# plugins
changelog = "2.5.0"
intelliJPlatform = "2.10.5"
kotlin = "2.2.21"
kover = "0.9.3"
qodana = "2025.2.2"

[libraries]
junit4 = { group = "junit", name = "junit", version.ref = "junit4" }
opentest4j = { group = "org.opentest4j", name = "opentest4j", version.ref = "opentest4j" }

# implementation
commons-text = { module = "org.apache.commons:commons-text", version.ref = "commons-text" }
jackson-kotlin = { module = "com.fasterxml.jackson.module:jackson-module-kotlin", version.ref = "jackson" }

# test
junit-vintage-engine = { module = "org.junit.vintage:junit-vintage-engine", version.ref = "junit" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit" }
assertk = { module = "com.willowtreeapps.assertk:assertk-jvm", version.ref = "assertk" }

[plugins]
changelog = { id = "org.jetbrains.changelog", version.ref = "changelog" }
intelliJPlatform = { id = "org.jetbrains.intellij.platform", version.ref = "intelliJPlatform" }
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kover = { id = "org.jetbrains.kotlinx.kover", version.ref = "kover" }
qodana = { id = "org.jetbrains.qodana", version.ref = "qodana" }
